import type { UserConfig, ScheduleData } from '@/types';

export const defaultConfig: UserConfig = {
  globalThresholds: {
    excellent: 90,
    good: 75,
    fair: 60,
  },
  categories: [
    {
      id: 'relationships',
      name: 'Relaciones',
      description: 'Integridad de relaciones y conexiones lógicas entre actividades',
      weight: 20,
      enabled: true,
      criteria: [
        {
          id: 'missing_predecessors',
          name: 'Predecesores Faltantes',
          description: 'Actividades sin predecesores que rompen la lógica de la red',
          category: 'relationships',
          enabled: true,
          weight: 25,
          threshold: { warning: 5, critical: 15 },
        },
        {
          id: 'missing_successors',
          name: 'Sucesores Faltantes',
          description: 'Actividades sin sucesores que crean extremos abiertos',
          category: 'relationships',
          enabled: true,
          weight: 25,
          threshold: { warning: 10, critical: 25 },
        },
        {
          id: 'open_ends',
          name: 'Extremos Abiertos',
          description: 'Actividades completamente desconectadas de la red',
          category: 'relationships',
          enabled: true,
          weight: 30,
          threshold: { warning: 2, critical: 5 },
        },
        {
          id: 'relationship_types',
          name: 'Distribución de Tipos',
          description: 'Balance apropiado de tipos de relación (FS, SS, FF, SF)',
          category: 'relationships',
          enabled: true,
          weight: 20,
          threshold: { warning: 70, critical: 50 },
        },
      ],
    },
    {
      id: 'constraints',
      name: 'Restricciones',
      description: 'Uso y apropiación de restricciones en el cronograma',
      weight: 15,
      enabled: true,
      criteria: [
        {
          id: 'hard_constraints',
          name: 'Restricciones Duras',
          description: 'Restricciones de tipo "Must Start/Finish On" que limitan la flexibilidad',
          category: 'constraints',
          enabled: true,
          weight: 35,
          threshold: { warning: 3, critical: 8 },
        },
        {
          id: 'soft_constraints',
          name: 'Restricciones Blandas',
          description: 'Restricciones de tipo "Start/Finish On or After/Before"',
          category: 'constraints',
          enabled: true,
          weight: 25,
          threshold: { warning: 10, critical: 20 },
        },
        {
          id: 'alap_constraints',
          name: 'Restricciones ALAP',
          description: 'Restricciones "As Late As Possible" que pueden causar confusión',
          category: 'constraints',
          enabled: true,
          weight: 20,
          threshold: { warning: 5, critical: 15 },
        },
        {
          id: 'multiple_constraints',
          name: 'Múltiples Restricciones',
          description: 'Actividades con más de una restricción aplicada',
          category: 'constraints',
          enabled: true,
          weight: 20,
          threshold: { warning: 2, critical: 5 },
        },
      ],
    },
    {
      id: 'logic_network',
      name: 'Lógica/Red',
      description: 'Integridad de la red y lógica del cronograma',
      weight: 20,
      enabled: true,
      criteria: [
        {
          id: 'circular_relationships',
          name: 'Relaciones Circulares',
          description: 'Ciclos de dependencias que impiden el cálculo de fechas',
          category: 'logic_network',
          enabled: true,
          weight: 40,
          threshold: { warning: 1, critical: 3 },
        },
        {
          id: 'negative_lag',
          name: 'Lag Negativo',
          description: 'Uso de lead (lag negativo) que puede causar problemas',
          category: 'logic_network',
          enabled: true,
          weight: 30,
          threshold: { warning: 2, critical: 5 },
        },
        {
          id: 'excessive_lag',
          name: 'Lag Excesivo',
          description: 'Relaciones con lag mayor a 30 días',
          category: 'logic_network',
          enabled: true,
          weight: 15,
          threshold: { warning: 5, critical: 10 },
        },
        {
          id: 'relationship_density',
          name: 'Densidad de Relaciones',
          description: 'Promedio de relaciones por actividad',
          category: 'logic_network',
          enabled: true,
          weight: 15,
          threshold: { warning: 1.5, critical: 1.0 },
        },
      ],
    },
    {
      id: 'duration',
      name: 'Duración',
      description: 'Razonabilidad de las duraciones de actividades',
      weight: 10,
      enabled: true,
      criteria: [
        {
          id: 'zero_duration',
          name: 'Duración Cero',
          description: 'Actividades de tarea con duración cero',
          category: 'duration',
          enabled: true,
          weight: 35,
          threshold: { warning: 2, critical: 5 },
        },
        {
          id: 'excessive_duration',
          name: 'Duración Excesiva',
          description: 'Actividades con duración mayor a 40 días',
          category: 'duration',
          enabled: true,
          weight: 35,
          threshold: { warning: 5, critical: 10 },
        },
        {
          id: 'unusual_duration',
          name: 'Duración Inusual',
          description: 'Duraciones que se desvían significativamente del promedio',
          category: 'duration',
          enabled: true,
          weight: 30,
          threshold: { warning: 10, critical: 20 },
        },
      ],
    },
    {
      id: 'calendar',
      name: 'Calendario',
      description: 'Asignación y consistencia de calendarios',
      weight: 10,
      enabled: true,
      criteria: [
        {
          id: 'missing_calendars',
          name: 'Calendarios Faltantes',
          description: 'Actividades sin calendario asignado',
          category: 'calendar',
          enabled: true,
          weight: 60,
          threshold: { warning: 1, critical: 5 },
        },
        {
          id: 'calendar_consistency',
          name: 'Consistencia de Calendarios',
          description: 'Uso consistente de calendarios en actividades relacionadas',
          category: 'calendar',
          enabled: true,
          weight: 40,
          threshold: { warning: 5, critical: 15 },
        },
      ],
    },
    {
      id: 'critical_path',
      name: 'Camino Crítico',
      description: 'Análisis del camino crítico y flotante',
      weight: 10,
      enabled: true,
      criteria: [
        {
          id: 'critical_path_length',
          name: 'Longitud del Camino Crítico',
          description: 'Porcentaje de actividades en el camino crítico',
          category: 'critical_path',
          enabled: true,
          weight: 50,
          threshold: { warning: 50, critical: 70 },
        },
        {
          id: 'negative_float',
          name: 'Flotante Negativo',
          description: 'Actividades con flotante negativo indicando retraso',
          category: 'critical_path',
          enabled: true,
          weight: 50,
          threshold: { warning: 1, critical: 5 },
        },
      ],
    },
    {
      id: 'data_quality',
      name: 'Calidad de Datos',
      description: 'Completitud y validez de los datos',
      weight: 10,
      enabled: true,
      criteria: [
        {
          id: 'missing_names',
          name: 'Nombres Faltantes',
          description: 'Actividades sin nombre descriptivo',
          category: 'data_quality',
          enabled: true,
          weight: 25,
          threshold: { warning: 1, critical: 5 },
        },
        {
          id: 'duplicate_ids',
          name: 'IDs Duplicados',
          description: 'Identificadores de actividad duplicados',
          category: 'data_quality',
          enabled: true,
          weight: 30,
          threshold: { warning: 1, critical: 3 },
        },
        {
          id: 'missing_wbs',
          name: 'WBS Faltante',
          description: 'Actividades sin asignación WBS',
          category: 'data_quality',
          enabled: true,
          weight: 25,
          threshold: { warning: 2, critical: 8 },
        },
        {
          id: 'invalid_dates',
          name: 'Fechas Inválidas',
          description: 'Inconsistencias en fechas de inicio/fin',
          category: 'data_quality',
          enabled: true,
          weight: 20,
          threshold: { warning: 5, critical: 15 },
        },
      ],
    },
    {
      id: 'progress',
      name: 'Progreso',
      description: 'Consistencia de progreso y estado',
      weight: 5,
      enabled: true,
      criteria: [
        {
          id: 'out_of_sequence',
          name: 'Progreso Fuera de Secuencia',
          description: 'Actividades con progreso que violan la lógica de red',
          category: 'progress',
          enabled: true,
          weight: 60,
          threshold: { warning: 3, critical: 8 },
        },
        {
          id: 'duration_inconsistencies',
          name: 'Inconsistencias de Duración',
          description: 'Discrepancias entre duración original y restante',
          category: 'progress',
          enabled: true,
          weight: 40,
          threshold: { warning: 5, critical: 12 },
        },
      ],
    },
  ],
};

// Datos de ejemplo de un cronograma de construcción
export const sampleScheduleData: ScheduleData = {
  activities: [
    { id: 'A1000', name: 'Mobilization', duration: 5, startDate: new Date('2026-01-01'), endDate: new Date('2026-01-06'), calendarId: 'CAL1', wbsCode: '1.1', isCritical: true, totalFloat: 0, percentComplete: 100 },
    { id: 'A1010', name: 'Site Preparation', duration: 10, startDate: new Date('2026-01-06'), endDate: new Date('2026-01-16'), calendarId: 'CAL1', wbsCode: '1.2', isCritical: true, totalFloat: 0, percentComplete: 100 },
    { id: 'A1020', name: 'Foundation Excavation', duration: 15, startDate: new Date('2026-01-16'), endDate: new Date('2026-01-31'), calendarId: 'CAL1', wbsCode: '1.3', isCritical: true, totalFloat: 0, percentComplete: 90 },
    { id: 'A1030', name: 'Foundation Reinforcement', duration: 8, startDate: new Date('2026-01-31'), endDate: new Date('2026-02-08'), calendarId: 'CAL1', wbsCode: '1.4', isCritical: true, totalFloat: 0, percentComplete: 50 },
    { id: 'A1040', name: 'Concrete Pouring', duration: 3, startDate: new Date('2026-02-08'), endDate: new Date('2026-02-11'), calendarId: 'CAL1', wbsCode: '1.5', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1050', name: 'Curing Period', duration: 7, startDate: new Date('2026-02-11'), endDate: new Date('2026-02-18'), calendarId: 'CAL1', wbsCode: '1.6', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1060', name: 'Structural Steel Delivery', duration: 2, startDate: new Date('2026-01-20'), endDate: new Date('2026-01-22'), calendarId: 'CAL1', wbsCode: '2.1', isCritical: false, totalFloat: 15, percentComplete: 80, constraintType: 'start', constraintDate: new Date('2026-01-20') },
    { id: 'A1070', name: 'Steel Column Erection', duration: 20, startDate: new Date('2026-02-18'), endDate: new Date('2026-03-10'), calendarId: 'CAL1', wbsCode: '2.2', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1080', name: 'Beam Installation', duration: 15, startDate: new Date('2026-03-10'), endDate: new Date('2026-03-25'), calendarId: 'CAL1', wbsCode: '2.3', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1090', name: 'Decking Installation', duration: 12, startDate: new Date('2026-03-25'), endDate: new Date('2026-04-06'), calendarId: 'CAL1', wbsCode: '2.4', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1100', name: 'Electrical Rough-in', duration: 25, startDate: new Date('2026-03-15'), endDate: new Date('2026-04-09'), calendarId: 'CAL1', wbsCode: '3.1', isCritical: false, totalFloat: 5, percentComplete: 0 },
    { id: 'A1110', name: 'Plumbing Rough-in', duration: 20, startDate: new Date('2026-03-20'), endDate: new Date('2026-04-09'), calendarId: 'CAL1', wbsCode: '3.2', isCritical: false, totalFloat: 5, percentComplete: 0 },
    { id: 'A1120', name: 'HVAC Installation', duration: 30, startDate: new Date('2026-04-06'), endDate: new Date('2026-05-06'), calendarId: 'CAL1', wbsCode: '3.3', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1130', name: 'Fire Protection', duration: 18, startDate: new Date('2026-04-09'), endDate: new Date('2026-04-27'), calendarId: 'CAL1', wbsCode: '3.4', isCritical: false, totalFloat: 9, percentComplete: 0 },
    { id: 'A1140', name: 'Interior Framing', duration: 35, startDate: new Date('2026-05-06'), endDate: new Date('2026-06-10'), calendarId: 'CAL1', wbsCode: '4.1', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1150', name: 'Drywall Installation', duration: 28, startDate: new Date('2026-06-10'), endDate: new Date('2026-07-08'), calendarId: 'CAL1', wbsCode: '4.2', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1160', name: 'Painting', duration: 21, startDate: new Date('2026-07-08'), endDate: new Date('2026-07-29'), calendarId: 'CAL1', wbsCode: '4.3', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1170', name: 'Flooring Installation', duration: 18, startDate: new Date('2026-07-15'), endDate: new Date('2026-08-02'), calendarId: 'CAL1', wbsCode: '4.4', isCritical: false, totalFloat: 7, percentComplete: 0 },
    { id: 'A1180', name: 'Ceiling Installation', duration: 15, startDate: new Date('2026-07-20'), endDate: new Date('2026-08-04'), calendarId: 'CAL1', wbsCode: '4.5', isCritical: false, totalFloat: 5, percentComplete: 0 },
    { id: 'A1190', name: 'Fixture Installation', duration: 12, startDate: new Date('2026-08-02'), endDate: new Date('2026-08-14'), calendarId: 'CAL1', wbsCode: '5.1', isCritical: false, totalFloat: 3, percentComplete: 0 },
    { id: 'A1200', name: 'Final Electrical', duration: 10, startDate: new Date('2026-08-04'), endDate: new Date('2026-08-14'), calendarId: 'CAL1', wbsCode: '5.2', isCritical: false, totalFloat: 3, percentComplete: 0 },
    { id: 'A1210', name: 'Final Plumbing', duration: 8, startDate: new Date('2026-08-06'), endDate: new Date('2026-08-14'), calendarId: 'CAL1', wbsCode: '5.3', isCritical: false, totalFloat: 3, percentComplete: 0 },
    { id: 'A1220', name: 'HVAC Commissioning', duration: 7, startDate: new Date('2026-08-14'), endDate: new Date('2026-08-21'), calendarId: 'CAL1', wbsCode: '5.4', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1230', name: 'Fire Alarm Testing', duration: 5, startDate: new Date('2026-08-16'), endDate: new Date('2026-08-21'), calendarId: 'CAL1', wbsCode: '5.5', isCritical: false, totalFloat: 2, percentComplete: 0 },
    { id: 'A1240', name: 'Elevator Installation', duration: 14, startDate: new Date('2026-07-29'), endDate: new Date('2026-08-12'), calendarId: 'CAL1', wbsCode: '5.6', isCritical: false, totalFloat: 5, percentComplete: 0 },
    { id: 'A1250', name: 'Landscaping', duration: 20, startDate: new Date('2026-08-10'), endDate: new Date('2026-08-30'), calendarId: 'CAL1', wbsCode: '6.1', isCritical: false, totalFloat: 5, percentComplete: 0 },
    { id: 'A1260', name: 'Parking Lot', duration: 15, startDate: new Date('2026-08-12'), endDate: new Date('2026-08-27'), calendarId: 'CAL1', wbsCode: '6.2', isCritical: false, totalFloat: 5, percentComplete: 0 },
    { id: 'A1270', name: 'Final Inspection', duration: 5, startDate: new Date('2026-08-21'), endDate: new Date('2026-08-26'), calendarId: 'CAL1', wbsCode: '7.1', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1280', name: 'Punch List', duration: 10, startDate: new Date('2026-08-26'), endDate: new Date('2026-09-05'), calendarId: 'CAL1', wbsCode: '7.2', isCritical: true, totalFloat: 0, percentComplete: 0 },
    { id: 'A1290', name: 'Project Closeout', duration: 5, startDate: new Date('2026-09-05'), endDate: new Date('2026-09-10'), calendarId: 'CAL1', wbsCode: '7.3', isCritical: true, totalFloat: 0, percentComplete: 0 },
    // Actividades con problemas intencionales para el demo
    { id: 'A1300', name: '', duration: 0, startDate: new Date('2026-02-01'), endDate: new Date('2026-02-01'), calendarId: 'CAL1', wbsCode: '8.1', isCritical: false, totalFloat: 30, percentComplete: 0 },
    { id: 'A1310', name: 'Long Activity Task', duration: 60, startDate: new Date('2026-03-01'), endDate: new Date('2026-04-30'), calendarId: 'CAL1', wbsCode: '8.2', isCritical: false, totalFloat: 10, percentComplete: 0 },
    { id: 'A1320', name: 'Activity With Hard Constraint', duration: 10, startDate: new Date('2026-04-01'), endDate: new Date('2026-04-11'), calendarId: 'CAL1', wbsCode: '8.3', isCritical: false, totalFloat: 5, percentComplete: 0, constraintType: 'finish', constraintDate: new Date('2026-04-11') },
    { id: 'A1330', name: 'Out of Sequence Task', duration: 8, startDate: new Date('2026-02-01'), endDate: new Date('2026-02-09'), calendarId: 'CAL1', wbsCode: '8.4', isCritical: false, totalFloat: 20, percentComplete: 50 },
    { id: 'A1340', name: 'Negative Float Task', duration: 12, startDate: new Date('2026-01-15'), endDate: new Date('2026-01-27'), calendarId: 'CAL1', wbsCode: '8.5', isCritical: true, totalFloat: -5, percentComplete: 80 },
    { id: 'A1350', name: 'Orphan Activity', duration: 5, startDate: new Date('2026-05-01'), endDate: new Date('2026-05-06'), calendarId: 'CAL1', wbsCode: '8.6', isCritical: false, totalFloat: 50, percentComplete: 0 },
  ],
  relationships: [
    { id: 'R001', predecessor: 'A1000', successor: 'A1010', type: 'FS', lag: 0 },
    { id: 'R002', predecessor: 'A1010', successor: 'A1020', type: 'FS', lag: 0 },
    { id: 'R003', predecessor: 'A1020', successor: 'A1030', type: 'FS', lag: 0 },
    { id: 'R004', predecessor: 'A1030', successor: 'A1040', type: 'FS', lag: 0 },
    { id: 'R005', predecessor: 'A1040', successor: 'A1050', type: 'FS', lag: 0 },
    { id: 'R006', predecessor: 'A1050', successor: 'A1070', type: 'FS', lag: 0 },
    { id: 'R007', predecessor: 'A1060', successor: 'A1070', type: 'FS', lag: 0 },
    { id: 'R008', predecessor: 'A1070', successor: 'A1080', type: 'FS', lag: 0 },
    { id: 'R009', predecessor: 'A1080', successor: 'A1090', type: 'FS', lag: 0 },
    { id: 'R010', predecessor: 'A1090', successor: 'A1120', type: 'FS', lag: 0 },
    { id: 'R011', predecessor: 'A1080', successor: 'A1100', type: 'SS', lag: 5 },
    { id: 'R012', predecessor: 'A1080', successor: 'A1110', type: 'SS', lag: 10 },
    { id: 'R013', predecessor: 'A1100', successor: 'A1130', type: 'FS', lag: 0 },
    { id: 'R014', predecessor: 'A1110', successor: 'A1130', type: 'FS', lag: 0 },
    { id: 'R015', predecessor: 'A1120', successor: 'A1140', type: 'FS', lag: 0 },
    { id: 'R016', predecessor: 'A1140', successor: 'A1150', type: 'FS', lag: 0 },
    { id: 'R017', predecessor: 'A1150', successor: 'A1160', type: 'FS', lag: 0 },
    { id: 'R018', predecessor: 'A1160', successor: 'A1170', type: 'SS', lag: 7 },
    { id: 'R019', predecessor: 'A1160', successor: 'A1180', type: 'SS', lag: 12 },
    { id: 'R020', predecessor: 'A1170', successor: 'A1190', type: 'FS', lag: 0 },
    { id: 'R021', predecessor: 'A1180', successor: 'A1190', type: 'FS', lag: 10 },
    { id: 'R022', predecessor: 'A1180', successor: 'A1200', type: 'FS', lag: 0 },
    { id: 'R023', predecessor: 'A1190', successor: 'A1210', type: 'FS', lag: 0 },
    { id: 'R024', predecessor: 'A1200', successor: 'A1220', type: 'FS', lag: 0 },
    { id: 'R025', predecessor: 'A1210', successor: 'A1220', type: 'FS', lag: 0 },
    { id: 'R026', predecessor: 'A1130', successor: 'A1230', type: 'FS', lag: 0 },
    { id: 'R027', predecessor: 'A1160', successor: 'A1240', type: 'FS', lag: 0 },
    { id: 'R028', predecessor: 'A1220', successor: 'A1270', type: 'FS', lag: 0 },
    { id: 'R029', predecessor: 'A1230', successor: 'A1270', type: 'FS', lag: 0 },
    { id: 'R030', predecessor: 'A1250', successor: 'A1270', type: 'FS', lag: 0 },
    { id: 'R031', predecessor: 'A1260', successor: 'A1270', type: 'FS', lag: 0 },
    { id: 'R032', predecessor: 'A1270', successor: 'A1280', type: 'FS', lag: 0 },
    { id: 'R033', predecessor: 'A1280', successor: 'A1290', type: 'FS', lag: 0 },
    // Relaciones con problemas
    { id: 'R034', predecessor: 'A1100', successor: 'A1110', type: 'FS', lag: -3 },
    { id: 'R035', predecessor: 'A1310', successor: 'A1330', type: 'FS', lag: 45 },
  ],
  calendars: [
    { id: 'CAL1', name: 'Standard 5-Day Workweek', workDays: [1, 2, 3, 4, 5], hoursPerDay: 8 },
    { id: 'CAL2', name: '7-Day Workweek', workDays: [0, 1, 2, 3, 4, 5, 6], hoursPerDay: 8 },
  ],
};
